-- MySQL Script generated by MySQL Workbench
-- 09/26/17 15:59:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_ventas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_ventas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_ventas` DEFAULT CHARACTER SET utf8 ;
USE `bd_ventas` ;

-- -----------------------------------------------------
-- Table `bd_ventas`.`tbl_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ventas`.`tbl_manager` (
  `idtbl_administrador` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idtbl_administrador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bd_ventas`.`tbl_agreement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ventas`.`tbl_agreement` (
  `idtbl_agreement` INT(11) NOT NULL AUTO_INCREMENT,
  `agreement` TINYTEXT NULL DEFAULT NULL,
  `help` TINYTEXT NULL DEFAULT NULL,
  `tbl_manager_idtbl_administrador` INT(11) NOT NULL,
  PRIMARY KEY (`idtbl_agreement`),
  INDEX `fk_tbl_agreement_tbl_manager1_idx` (`tbl_manager_idtbl_administrador` ASC),
  CONSTRAINT `fk_tbl_agreement_tbl_manager1`
    FOREIGN KEY (`tbl_manager_idtbl_administrador`)
    REFERENCES `bd_ventas`.`tbl_manager` (`idtbl_administrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bd_ventas`.`tbl_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ventas`.`tbl_categories` (
  `idtbl_categorias` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` TEXT NOT NULL,
  PRIMARY KEY (`idtbl_categorias`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bd_ventas`.`tbl_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ventas`.`tbl_user` (
  `idtbl_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(45) NULL DEFAULT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `cedula` INT(11) NOT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` INT(15) NOT NULL,
  `tipo` VARCHAR(50) NOT NULL,
  `foto` VARCHAR(200) NOT NULL,
  `estado` VARCHAR(10) NOT NULL,
  `tbl_contract_idtbl_contract` INT(11) NOT NULL,
  PRIMARY KEY (`idtbl_usuario`),
  INDEX `fk_tbl_user_tbl_contract1_idx` (`tbl_contract_idtbl_contract` ASC),
  CONSTRAINT `fk_tbl_user_tbl_contract1`
    FOREIGN KEY (`tbl_contract_idtbl_contract`)
    REFERENCES `bd_ventas`.`tbl_agreement` (`idtbl_agreement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bd_ventas`.`tbl_seller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ventas`.`tbl_seller` (
  `idtbl_vendedor` INT(11) NOT NULL AUTO_INCREMENT,
  `tbl_contract_idtbl_contract` INT(11) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `nombre_usuario` VARCHAR(20) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `correo` VARCHAR(50) NOT NULL,
  `cedula_juridica` INT(20) NOT NULL,
  `estado` VARCHAR(10) NOT NULL,
  `foto` VARCHAR(100) NOT NULL,
  `telefono` INT(10) NOT NULL,
  PRIMARY KEY (`idtbl_vendedor`),
  INDEX `fk_tbl_vendedor_tbl_contract1_idx` (`tbl_contract_idtbl_contract` ASC),
  CONSTRAINT `fk_tbl_vendedor_tbl_contract1`
    FOREIGN KEY (`tbl_contract_idtbl_contract`)
    REFERENCES `bd_ventas`.`tbl_agreement` (`idtbl_agreement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bd_ventas`.`tbl_subcategorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ventas`.`tbl_subcategorias` (
  `idtbl_subcategorias` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_subcategoria` VARCHAR(45) NULL DEFAULT NULL,
  `tbl_categorias_idtbl_categorias` INT(11) NOT NULL,
  PRIMARY KEY (`idtbl_subcategorias`),
  INDEX `fk_tbl_subcategorias_tbl_categorias1_idx` (`tbl_categorias_idtbl_categorias` ASC),
  CONSTRAINT `fk_tbl_subcategorias_tbl_categorias1`
    FOREIGN KEY (`tbl_categorias_idtbl_categorias`)
    REFERENCES `bd_ventas`.`tbl_categories` (`idtbl_categorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bd_ventas`.`tbl_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ventas`.`tbl_productos` (
  `idtbl_productos` INT(11) NOT NULL AUTO_INCREMENT,
  `tbl_vendedor_idtbl_vendedor` INT(11) NOT NULL,
  `tbl_subcategorias_idtbl_subcategorias` INT(11) NOT NULL,
  `Peso` VARCHAR(45) NULL DEFAULT NULL,
  `color` VARCHAR(45) NULL DEFAULT NULL,
  `ancho` VARCHAR(45) NULL DEFAULT NULL,
  `altura` VARCHAR(45) NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  `price_shipping` VARCHAR(45) NULL DEFAULT NULL,
  `cantidad` INT(11) NOT NULL,
  `tama` VARCHAR(11) NOT NULL,
  `precio` INT(15) NOT NULL,
  `titulo` VARCHAR(20) NOT NULL,
  `garantia` VARCHAR(50) NOT NULL,
  `descripcion` TEXT NOT NULL,
  PRIMARY KEY (`idtbl_productos`),
  INDEX `fk_tbl_productos_tbl_vendedor_idx` (`tbl_vendedor_idtbl_vendedor` ASC),
  INDEX `fk_tbl_productos_tbl_subcategorias1_idx` (`tbl_subcategorias_idtbl_subcategorias` ASC),
  CONSTRAINT `tbl_productos_ibfk_1`
    FOREIGN KEY (`tbl_vendedor_idtbl_vendedor`)
    REFERENCES `bd_ventas`.`tbl_seller` (`idtbl_vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tbl_productos_ibfk_2`
    FOREIGN KEY (`tbl_subcategorias_idtbl_subcategorias`)
    REFERENCES `bd_ventas`.`tbl_subcategorias` (`idtbl_subcategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bd_ventas`.`tbl_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ventas`.`tbl_comments` (
  `idtbl_comments` INT(11) NOT NULL AUTO_INCREMENT,
  `comments` VARCHAR(45) NULL DEFAULT NULL,
  `tbl_user_idtbl_usuario` INT(11) NOT NULL,
  `tbl_productos_idtbl_productos` INT(11) NOT NULL,
  PRIMARY KEY (`idtbl_comments`),
  INDEX `fk_tbl_comments_tbl_user1_idx` (`tbl_user_idtbl_usuario` ASC),
  INDEX `fk_tbl_comments_tbl_productos1_idx` (`tbl_productos_idtbl_productos` ASC),
  CONSTRAINT `fk_tbl_comments_tbl_user1`
    FOREIGN KEY (`tbl_user_idtbl_usuario`)
    REFERENCES `bd_ventas`.`tbl_user` (`idtbl_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_comments_tbl_productos1`
    FOREIGN KEY (`tbl_productos_idtbl_productos`)
    REFERENCES `bd_ventas`.`tbl_productos` (`idtbl_productos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bd_ventas`.`tbl_message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ventas`.`tbl_message` (
  `idtbl_message` INT(11) NOT NULL AUTO_INCREMENT,
  `tbl_user_idtbl_usuario` INT(11) NOT NULL,
  `tbl_vendedor_idtbl_vendedor` INT(11) NOT NULL,
  `message` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idtbl_message`),
  INDEX `fk_tbl_message_tbl_user1_idx` (`tbl_user_idtbl_usuario` ASC),
  INDEX `fk_tbl_message_tbl_vendedor1_idx` (`tbl_vendedor_idtbl_vendedor` ASC),
  CONSTRAINT `fk_tbl_message_tbl_user1`
    FOREIGN KEY (`tbl_user_idtbl_usuario`)
    REFERENCES `bd_ventas`.`tbl_user` (`idtbl_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_message_tbl_vendedor1`
    FOREIGN KEY (`tbl_vendedor_idtbl_vendedor`)
    REFERENCES `bd_ventas`.`tbl_seller` (`idtbl_vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bd_ventas`.`tbl_photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ventas`.`tbl_photo` (
  `idtbl_photo` INT(11) NOT NULL AUTO_INCREMENT,
  `picture_code` VARCHAR(45) NULL DEFAULT NULL,
  `tbl_productos_idtbl_productos` INT(11) NOT NULL,
  PRIMARY KEY (`idtbl_photo`),
  INDEX `fk_tbl_photo_tbl_productos1_idx` (`tbl_productos_idtbl_productos` ASC),
  CONSTRAINT `tbl_photo_ibfk_1`
    FOREIGN KEY (`tbl_productos_idtbl_productos`)
    REFERENCES `bd_ventas`.`tbl_productos` (`idtbl_productos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bd_ventas`.`tbl_ranking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ventas`.`tbl_ranking` (
  `idtbl_ranking` INT(11) NOT NULL AUTO_INCREMENT,
  `tbl_vendedor_idtbl_vendedor` INT(11) NOT NULL,
  `value_ranking` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idtbl_ranking`),
  INDEX `fk_tbl_ranking_tbl_vendedor1_idx` (`tbl_vendedor_idtbl_vendedor` ASC),
  CONSTRAINT `fk_tbl_ranking_tbl_vendedor1`
    FOREIGN KEY (`tbl_vendedor_idtbl_vendedor`)
    REFERENCES `bd_ventas`.`tbl_seller` (`idtbl_vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bd_ventas`.`tbl_record_seller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ventas`.`tbl_record_seller` (
  `idtbl_historial_vendedor` INT(11) NOT NULL AUTO_INCREMENT,
  `tbl_vendedor_idtbl_vendedor` INT(11) NOT NULL,
  PRIMARY KEY (`idtbl_historial_vendedor`),
  INDEX `fk_tbl_historial_vendedor_tbl_vendedor1_idx` (`tbl_vendedor_idtbl_vendedor` ASC),
  CONSTRAINT `fk_tbl_historial_vendedor_tbl_vendedor1`
    FOREIGN KEY (`tbl_vendedor_idtbl_vendedor`)
    REFERENCES `bd_ventas`.`tbl_seller` (`idtbl_vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bd_ventas`.`tbl_sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ventas`.`tbl_sales` (
  `idtbl_ventas` INT(11) NOT NULL AUTO_INCREMENT,
  `tbl_usuario_idtbl_usuario` INT(11) NOT NULL,
  `tbl_productos_idtbl_productos` INT(11) NOT NULL,
  PRIMARY KEY (`idtbl_ventas`),
  INDEX `fk_tbl_ventas_tbl_usuario1_idx` (`tbl_usuario_idtbl_usuario` ASC),
  INDEX `fk_tbl_ventas_tbl_productos1_idx` (`tbl_productos_idtbl_productos` ASC),
  CONSTRAINT `tbl_sales_ibfk_1`
    FOREIGN KEY (`tbl_productos_idtbl_productos`)
    REFERENCES `bd_ventas`.`tbl_productos` (`idtbl_productos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tbl_sales_ibfk_2`
    FOREIGN KEY (`tbl_usuario_idtbl_usuario`)
    REFERENCES `bd_ventas`.`tbl_user` (`idtbl_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

USE `bd_ventas` ;

-- -----------------------------------------------------
-- procedure insertar
-- -----------------------------------------------------

DELIMITER $$
USE `bd_ventas`$$
--
-- Procedimientos
--
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertar` (IN `idvendedor` INT, IN `idsubcategoria` INT, IN `pesos` VARCHAR(5), IN `colores` VARCHAR(20), IN `anchos` VARCHAR(10), IN `alturas` VARCHAR(10), IN `estados` VARCHAR(20), IN `precio_envios` INT(15), IN `cantidades` INT(10), IN `tamas` VARCHAR(10), IN `precios` INT(15), IN `titulos` VARCHAR(100), IN `garantias` VARCHAR(20), IN `descripciones` VARCHAR(500))  BEGIN


 INSERT INTO tbl_productos(idtbl_productos,tbl_vendedor_idtbl_vendedor,tbl_subcategorias_idtbl_subcategorias,Peso,color,ancho,altura,estado,price_shipping,cantidad,tama,precio,titulo,garantia,descripcion) VALUES('',idvendedor ,idsubcategoria,pesos,colores,anchos,alturas,estados,precio_envios,cantidades,tamas,precios,titulos,garantias,descripciones);
 

END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
